### ISSUE TITLE
This is superb work!

### ISSUE THREAD

**Issue by metkhoo** [SPFxAppDev/sp-map-webpart#5]
Just wanted to say how impressed I was with this web part.
Just some ideas...
1) Allow the pins to be defined in a SharePoint list
2) Allow "user" pins to pop up the SharePoint user profile 

But superb work here...

**Comment by metkhoo** [comment]
Another small point.  It would be great to have a pin or location as "default" so that the web part didn't always open in London.  Did I miss something there?
Thanks

**Comment by SPFxAppDev** [comment]
@metkhoo Thank you very much for the great feedback. Regarding the "default" location. This is possible. Go to your preferred location in edit mode, then right click and select the second menu item "Make this view as start position". This action saves the zoom level and the centred longitude and latitude. 

Regarding 

Point 1: what is the use case?

Point 2: You mean that you have the possibility to open the profile by clicking in a dialog? That should also work with the current solution. Just enter the URL to the profile in the marker type "URL" and select "embedded".

**Comment by metkhoo** [comment]
Regarding 1) Use case. 
Very often, the person in charge of the configuration is not allowed to edit the layout of a page so does not get Edit rights to the SitePages library.  However, that same person will be responsible to edit the locations of persons.  If there was a custom list in which they had "Contribute" rights then they could modify the pins from there to be shown on the web part.

I do though appreciate that there is so much functionality you have put into the "Edit web part" mode that it would lose some of the visual flexibility of the web part.

Again, very nice work here

**Comment by SPFxAppDev** [comment]
@metkhoo Thanks for the fast response. I have already thought about the list. But in my opinion this is not so flexible and not really useful for the (list) editor. Because this person has to enter the the longitude/latitude values in the list item (that could be error-prone). 

But you could e.g. give this "editor" the rights for the page (if possible). By the way: you can create a page as a "single part app page". In this case, no other web parts can be placed on the page.

**Comment by metkhoo** [comment]
@SPFxAppDev Yes, I totally understand your approach there.  Longitude and Latitude are very unfriendly and typing is definitely prone to mistakes.
Thanks for making this available.

**Comment by SPFxAppDev** [comment]
@metkhoo Regarding the other points (default location + user pin): Any questions? Or maybe the "User Pin" is not what you had in mind

**Comment by metkhoo** [comment]
@SPFxAppDev  Had a thought....
Any chance of putting in an image URL for the marker?  It may then be possible to add this as the source:

/_layouts/15/userphoto.aspx?size=S&amp;accountname={username}%40{domain}

Which should then show the SharePoint user profile photo as a marker
;-)

**Comment by SPFxAppDev** [comment]
@metkhoo Okay, I understand. Yes, theoretically it is possible to implement. But I think the marker should be big enough to identify the person, and that makes the UI a little "crazy" (if there are more than 10 markers in the vicinity). If the height of the marker is unchanged, then it is too small to identify the person. Let me think about it for the next version :) Thanks again for your feedback and ideas

**Comment by metkhoo** [comment]
@SPFxAppDev Have you considered submitting this to the PnP sample web parts community?

**Comment by SPFxAppDev** [comment]
@metkhoo I should probably do that, but the "Add a sample" page is "coming soon" and I don't have Twitter to submit my solution :D And I'm not aware of other ways to submit an example. Or do you have an alternative way?

**Comment by metkhoo** [comment]
Personally, if the process is difficult, I would go and select an existing PnP web part randomly then see if I could get the email address of one of the existing MVP contributors and then ask them via email.
They are normally very helpful people.,
;-)

**Comment by SPFxAppDev** [comment]
Thanks. Will try that
